services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payload
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

volumes:
  postgres:
  redis:
